version: '3'
services:
  mongodb-server:
    image: mongo:4.0.24
    restart: always
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: secret
  
 # mongo-express:
 #   image: mongo-express
 #   restart: always
 #   ports:
 #    - "8081:8081"
volumes:
  mongo-data: